name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          gradle-distribution-sha-256-sum-warning: false
      - name: build
        run: ./gradlew configureClientLaunch
      - name: build
        run: ./gradlew configureLaunch
      - name: build
        run: ./gradlew downloadAssets
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          # TODO Move jars
          path: .
