name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [17.0.8+7,]
        os: [ubuntu-22.04,]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          gradle-distribution-sha-256-sum-warning: false
      - name: capture build artifacts
        if: ${{ matrix.java == '17.0.8+7' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
